# get cookies
> curl -c cookies.txt localhost
> cat cookies.txt

# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

localhost       FALSE   /       FALSE   0       cookie  2e74b4a1ba7f3e40ab387166165f908f

# curl with cookie
> curl localhost -b "cookie=2e74b4a1ba7f3e40ab387166165f908f" 
